### ISSUE TITLE
選択テキストから日付を抽出できない場合、テキストをタイトルにしてほしいです。

### ISSUE THREAD

**Issue by shimataro** [retrorocket/Right-Click-to-Calendar#1]
便利な拡張機能を使わせてもらっています。

タイトルの通りですが、選択したテキストから日付を抽出できない場合、カレンダーのタイトルにテキストが入ったら便利だなと思いました。
（例えば「会食」というテキストを選択した場合、タイトルに「会食」と入るイメージです）

よろしければ検討していただけると助かります。

**Comment by retrorocket** [comment]
ご利用ありがとうございます。
v3.8.1で対応いたしました。正常に動作しないようであればお手数ですがご連絡ください。

動作確認を実施したChromeのバージョン：
74.0.3729.169（Official Build） （64 ビット）
