### ISSUE TITLE
Edgeを使用するとEdgeがクラッシュする

### ISSUE THREAD

**Issue by tekkotsu** [retrorocket/Right-Click-to-Calendar#47]
@retrorocket 

初回利用時
extension://femihkgadmhfmdlkjjfjcgleppfggadk/options.html
を開き、Chromium用オプションにチェックを入れ、リロードするとEdgeがクラッシュします。
ただし、全く同じOSでEdgeのバージョンも同じPC2台のうち、クラッシュするのは1台だけ、片方は正常に動作します。

Edge
バージョン 97.0.1072.55 (公式ビルド) (64 ビット)
OS
Windows 10 Pro 21H2 19044.1415

クラッシュするため開発者ツールは開けません。エラーダンプはとれませんでした。
この報告をするためだけにアカウントを作成しましたので、できれば調べてほしいです。

クラッシュしたPCでSleipnirに同じことをしましたが、Sleipnirでは動作します。

**Comment by retrorocket** [comment]
@tekkotsu 

報告ありがとうございます。
私の手元の同一環境では再現できなかったため、MicrosoftのTech Communityを検索したところ、
以下の投稿が見つかりました。Edgeのバグのようです。
[Re: Edge Stable crashing on extension function chrome\.identity\.launchWebAuthFlow \- Microsoft Tech Community](https://techcommunity.microsoft.com/t5/discussions/edge-stable-crashing-on-extension-function-chrome-identity/m-p/3027524#M51096)

本拡張にて、クラッシュの原因となっているAPIを利用している箇所は以下です。
https://github.com/retrorocket/Right-Click-to-Calendar/blob/6abb0a6d6e73412cd2f940368ef172c3b5b40605/app/assets/js/options.js#L83-L85

クラッシュの原因となっているAPIを使用せずに実装する方法もあるにはあるのですが、
恐らく極一部の環境でしか発症しないことと、
開発者の環境で事象が再現できず、修正できたか否かを確認する手段がないため、
Edgeが修正されるのを待っていただきたいです。

**Comment by retrorocket** [comment]
3.11で通信先をretrorocket.bizからgoogleapiに変更したが、本番用のアプリ、かつWindows 11 proでだけ再現するようになった。開発用アプリでは再現できない。

**Comment by retrorocket** [comment]
https://techcommunity.microsoft.com/t5/discussions/edge-stable-crashing-on-extension-function-chrome-identity/m-p/3190064/highlight/true#M52215

> The fix is now available in Edge Beta 99.0.1150.19+ and it should reach stable early March when 99 goes into stable. Let us know if there is any other feedback or issues.

3月頭には解決しそう…。

**Comment by tekkotsu** [comment]
@retrorocket 
バージョン 99.0.1150.30 (公式ビルド) (64 ビット)
で解消しました。
Tech Communityへの働きかけありがとうございました
