### ISSUE TITLE
vivaldiでトークンが存在しないため承認出来ないというエラーが出る

### ISSUE THREAD

**Issue by Reyt0m** [retrorocket/Right-Click-to-Calendar#55]
![image](https://user-images.githubusercontent.com/62173915/160973299-25b2bd2d-9f94-4e4d-911a-f754a606903a.png)

**Comment by retrorocket** [comment]
@Reyt0m 
ご利用ありがとうございます。このスクリーンショットだけでは
何が問題なのか、何を調査してほしいのかが一切わからないため、
恐れ入りますが、以下を教えていただけますでしょうか？

* お使いのOS, Vivaldi のバージョン
* どのような操作をしたときに上記のエラーが発生するのか
* エラーの解消のために試した操作があれば、その内容

また、調査をスムーズに行うため、issue のタイトル、もしくは報告する内容は起こっている事象を正確に記載いただけると幸いです。

**トークンが存在しないため承認出来ないというエラーが出る** とのことですが、
実際に発生しているエラー内容は
**トークンが存在しないため、予定が登録できないエラーが出る** のように見受けられます。
この拡張に限らず、何らかのトークンを使用するアプリケーションは、**登録用のトークンを取得するために、ユーザーにアプリケーションの承認を行ってもらう**という処理を行うため、トークンが存在しないためアプリケーションが承認出来ないという流れにはなりえません。

---

なお、スクリーンショットの内容のエラーはトークンの有効期限が切れているときにも表示されるため、メッセージ通りオプションページでリロードした上でアプリケーションを承認いただければ解消する想定でいます。

手元の 
Windows 10 Pro 21H2 19044.1586
5.1.2567.73 (Stable channel) (64-bit) 
環境では v3.11.1 が正常に動作することを確認しました。

**Comment by Reyt0m** [comment]
ご対応ありがとうございます。

1.  os : Windows 10 Pro 21H1 19043.1586
2.  vivaldi : 5.1.2567.73 (Stable channel) (64-bit) 
3.  操作 : オプション画面にてリロードした際に上記画像の様なエラーが報告される。
詳細_ 拡張機能のうち、 Autopagerize, Bitwarden,Mate Translate, MolyHaH のどれかが起動している状態で、リロードした場合にエラーが確認された。Bitwardenについては、認証画面が出るものの、即座に閉じてしまう。

よろしくお願いいたします。

**Comment by retrorocket** [comment]
@Reyt0m 
詳細のご連絡ありがとうございます。こちらの環境でも再現しました。
検証の結果 Vivaldi 5.1 以降のバグの可能性が高かったため、
Vivaldi の不具合報告フォームで報告しました。
https://forum.vivaldi.net/topic/73666/%E3%83%87%E3%82%B9%E3%82%AF%E3%83%88%E3%83%83%E3%83%97%E7%89%88-vivaldi-5-1-2567-33%E4%BB%A5%E9%99%8D-%E7%89%B9%E5%AE%9A%E6%9D%A1%E4%BB%B6%E3%82%92%E6%BA%80%E3%81%9F%E3%81%99%E3%81%A8%E6%8B%A1%E5%BC%B5%E6%A9%9F%E8%83%BD%E3%81%A7chrome-identity-launchwebauthflow%E3%81%8C%E4%BD%BF%E7%94%A8%E3%81%A7%E3%81%8D%E3%81%AA%E3%81%84

**Comment by Reyt0m** [comment]
ご対応ありがとうございます。

**Comment by retrorocket** [comment]
@Reyt0m
手元の環境では Vivaldi 5.2.2623.24 (Stable channel) (64-bit)  で事象が再現しなくなりました。お手すきの際に確認いただければ幸いです。

**Comment by Reyt0m** [comment]
こちらでも正常に稼働しているのが確認されました。

**Comment by retrorocket** [comment]
* Vivaldi の不具合報告フォームで事象が再現しなくなった旨を連絡しました。
* 問題が解消したためクローズします。再発した場合は本issueを再オープンしてください。
