### ISSUE TITLE
Edgeだとブラウザの起動ごとにGoogleへのログインが必要になる

### ISSUE THREAD

**Issue by tekkotsu** [retrorocket/Right-Click-to-Calendar#74]
Edgeだとブラウザを起動するたびにGoogleへのログインが必要になる上に、IDとPWの再入力と2段階認証もやり直しになり不便です。
Chromeだとこのようなことはなく快適に使えます。どうにか同じ仕様にできないものでしょうか？
1年我慢しましたが慣れなかったので解決してほしいです。

**Comment by tekkotsu** [comment]
@retrorocket アップデートでかなり使いやすくなりました。毎回ウインドウを手動で閉じるのさえなんとかなればもう言うことはないです。

**Comment by tekkotsu** [comment]
@retrorocket 言うことなしです。ありがとうございました。

**Comment by retrorocket** [comment]
v3.42でリリースしました。クローズします。
