### ISSUE TITLE
VivaldiだとGoogle認証後にwindow.close()されない

### ISSUE THREAD

**Issue by tekkotu** [retrorocket/Right-Click-to-Calendar#84]
環境
Vivaldi 6.1.3035.111 (Stable channel) (64-bit) 

Google認証すると空白のページにジャンプしますが、window.close()されません。
空白ページのアドレスは chrome-extension://femihkgadmhfmdlkjjfjcgleppfggadk/gettoken.html 
開発者コンソールの表示は [Scripts may close only the windows that were opened by them. ](gettoken.js:32 Scripts may close only the windows that were opened by them.)です

Edgeだと再現しません。

**Comment by retrorocket** [comment]
@tekkotu 返信が遅くなってしまい申し訳ありません。事象を確認いたしました。
Vivaldiのみ他のChromium系ブラウザと挙動が異なることが原因です。
Vivaldiのみで発生する事象のため、即時の対応は難しいです。ご期待に添えずすみません。

## 背景 

`window.close()`は「[ウインドウに履歴が一つの場合は動作する](https://html.spec.whatwg.org/multipage/nav-history-apis.html#dom-window-close)」という規定になっています。
Vivaldiのみ、本来は含まれないはずのGoogleのログイン画面を履歴に含めてしまうため、`window.close()`が想定通り動作しません。
他のChromium系のブラウザと挙動が異なるのですが、Vivaldiが意図的にこの挙動にしているのかは不明です。

## できそうな対応案

対応案はあるにはあるのですが、現在体調が芳しくなく療養中なこともあり、Vivaldiのためだけに動くには負担が大きいです。ご了承ください。

* `window.close()`を使わず[`chrome.windows.remove()`](https://developer.chrome.com/docs/extensions/reference/windows/#method-remove)を使用する
* なんでこんな挙動になってるのかVivaldiのユーザーフォーラムに質問を投げてみる。

**Comment by retrorocket** [comment]
Vivaldi 6.1.3035.302 (Stable channel) (64-bit) 
Edge バージョン 116.0.1938.62 (公式ビルド) (64 ビット)

上記ブラウザで問題が解消されたことを確認しました。クローズします。
